language: python
python:
 - "2.7"
install:
 - pip install flake8 stripe
 - pip install -r requirements.txt
 - pip install coveralls
script:
 #- flake8 `find . -iname "*.py" -not -ipath "*migration*"`
 - ./runtests.sh
after_success:
 - coveralls
notifications:
  slack:
    rooms:
      - readthedocs:y3hjODOi7EIz1JAbD1Zb41sz#general
    on_success: change
    on_failure: always
