# docker-compose-pypi.yml starts "devpi" service for local cache
version: '3'

volumes:
  devpi:

services:

  devpi:
    build:
      context: .
      dockerfile: ${PWD}/docker/Dockerfile.devpi
    ports:
      - "3141:3141"
    volumes:
      - devpi:/devpi
